@startuml
hide circle
skinparam classAttributeIconSize 0

interface Parser
class RemarkCommandParser {
  +parse(args: String): RemarkCommand
}
class ParseException

RemarkCommandParser ..|> Parser
RemarkCommandParser ..> ParseException : throws
@enduml
