@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CommandRegistry" as CommandRegistry LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "context:CommandContext" as CommandContext LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant ":Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

AddressBookParser -> CommandRegistry : parse("delete", " 1", currentMode)
activate CommandRegistry

CommandRegistry -> DeleteCommandParser : parse(" 1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand : DeleteCommand(index)
activate DeleteCommand
DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> CommandRegistry : d
deactivate DeleteCommandParser

CommandRegistry --> AddressBookParser : d
deactivate CommandRegistry

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

create CommandContext
LogicManager -> CommandContext : CommandContext(model, currentMode)
activate CommandContext
CommandContext --> LogicManager : context
deactivate CommandContext

LogicManager -> DeleteCommand : execute(context)
activate DeleteCommand

DeleteCommand -> CommandContext : getModel()
activate CommandContext
CommandContext --> DeleteCommand : model
deactivate CommandContext

DeleteCommand -> CommandContext : getAppMode()
activate CommandContext
CommandContext --> DeleteCommand : currentMode
deactivate CommandContext

DeleteCommand -> Model : getFilteredPersonList(currentMode)
activate Model
Model --> DeleteCommand : lastShownList
deactivate Model

DeleteCommand -> Model : deletePerson(personToDelete, currentMode)
activate Model
Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult : CommandResult(feedback)
activate CommandResult
CommandResult --> DeleteCommand : r
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

LogicManager -> Model : getAddressBook()
activate Model
Model --> LogicManager : addressBook
deactivate Model

LogicManager -> Storage : saveAddressBook(addressBook)
activate Storage
Storage --> LogicManager
deactivate Storage

[<-- LogicManager : r
deactivate LogicManager
@enduml

