@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CommandRegistry" as CommandRegistry LOGIC_COLOR
participant ":UnlockCommandParser" as UnlockCommandParser LOGIC_COLOR
participant "uc:UnlockCommand" as UnlockCommand LOGIC_COLOR
participant "context:CommandContext" as CommandContext LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("unlock myPassword123")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("unlock myPassword123")
activate AddressBookParser

AddressBookParser -> CommandRegistry : parse("unlock", " myPassword123", currentMode)
activate CommandRegistry

CommandRegistry -> UnlockCommandParser : parse(" myPassword123")
activate UnlockCommandParser

create UnlockCommand
UnlockCommandParser -> UnlockCommand : UnlockCommand(password)
activate UnlockCommand
UnlockCommand --> UnlockCommandParser : uc
deactivate UnlockCommand

UnlockCommandParser --> CommandRegistry : uc
deactivate UnlockCommandParser

CommandRegistry --> AddressBookParser : uc
deactivate CommandRegistry
destroy UnlockCommandParser

AddressBookParser --> LogicManager : uc
deactivate AddressBookParser

create CommandContext
LogicManager -> CommandContext : CommandContext(model, currentMode)
activate CommandContext
CommandContext --> LogicManager : context
deactivate CommandContext

LogicManager -> UnlockCommand : execute(context)
activate UnlockCommand

UnlockCommand -> CommandContext : getModel()
activate CommandContext
CommandContext --> UnlockCommand : model
deactivate CommandContext

UnlockCommand -> CommandContext : getAppMode()
activate CommandContext
CommandContext --> UnlockCommand : currentMode
deactivate CommandContext

UnlockCommand -> Model : getAddressBookPassword()
activate Model
Model --> UnlockCommand : storedPassword
deactivate Model

alt password matches
    create CommandResult
    UnlockCommand -> CommandResult ++ : CommandResult(feedback,requestedMode=UNLOCKED)
    CommandResult --> UnlockCommand : r
    deactivate CommandResult

    UnlockCommand --> LogicManager : r
    deactivate UnlockCommand

    [<-- LogicManager : r
else password does not match
    UnlockCommand --> LogicManager : throws CommandException
    deactivate UnlockCommand
    [<-- LogicManager
end

deactivate LogicManager
@enduml
